---
title: "group_assignment_F7"
author: "julie, Martin, cecilie, Amanda"
format: html
editor: visual
---

## Load libraries

```{r}
#| message: false

library("dplyr")
library("tidyverse")
library("here")
library("ggraph")
library("ggridges")
library("stringr")
library("RColorBrewer")
library("ggthemes")
library("ggseqlogo")
library("purrr")
library("modelr")
library("broom")

```

## Load data

```{r}
biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

### Data wrangling

```{r}
write_csv(x = biopsy, file = "data/biopsy.csv")

```

### Principal Component analysis

```{r}
pca_fit <- biopsy |> # make a PCA fit
  select(where(is.numeric)) |> # choose only numeric values
  prcomp(scale = TRUE) 
```

```{r}
pca_fit |> 
  augment(biopsy) |> # include original data
  ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) + # make ggplot
  geom_point(size = 2) + # chose size of points
  labs(                         # add x- and y-axis labels
    x = "Principal Component 1",
    y = "Principal Component 2",
    title = "PCA of Biopsy Data"
  ) +
  scale_color_manual(        # add colors depending on benign or malignant
    values = c(
      malignant = "red", 
      benign = "green")
  ) 
```
